# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '数据存储' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'FMDB'
  # Pods for 数据存储
    
  target '数据存储Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '数据存储UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
